openapi: 3.0.3
paths:

  /compare:
    post:
      tags:
        - matching
      summary: "Compare provided face images in all combinations and return similarity score for each pair."
      operationId: compare
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompareRequest"
      responses:
        200:
          description: "Successful operation; return compare results with their score and similarity."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompareResponse"
        400:
          $ref: "./common.yml#/components/responses/BadRequest"
        403:
          $ref: "./common.yml#/components/responses/BadLicense"

components:
  schemas:

    CompareRequest:
      type: object
      required:
        - images
      properties:
        thumbnails:
          type: boolean
          default: false
        images:
          type: array
          items:
            $ref: "#/components/schemas/CompareImage"

    CompareImageIndex:
      type: integer
      description: "Image index used to identify input photos between themselves.
      If not specified, than input list index is used"

    CompareFaceIndex:
      type: integer
      description: "Faces index used to identify faces in scope of one photo."

    CompareImage:
      type: object
      required:
        - data
      properties:
        index:
          $ref: "#/components/schemas/CompareImageIndex"
        type:
          $ref: "#/components/schemas/ImageSource"
        data:
          $ref: "./common.yml#/components/schemas/ImageData"

    CompareResponse:
      allOf:
        - $ref: './common.yml#/components/schemas/FaceRecognitionResult'
        - type: object
          properties:
            results:
              type: array
              items:
                $ref: "#/components/schemas/CompareImageResult"
            detections:
              type: array
              items:
                $ref: "#/components/schemas/CompareImageDetection"

    CompareImageResult:
      type: object
      required:
        - firstIndex
        - secondIndex
      properties:
        firstIndex:
          $ref: "#/components/schemas/CompareImageIndex"
        firstFaceIndex:
          $ref: "#/components/schemas/CompareFaceIndex"
        secondIndex:
          $ref: "#/components/schemas/CompareImageIndex"
        secondFaceIndex:
          $ref: "#/components/schemas/CompareFaceIndex"
        score:
          type: number
        similarity:
          type: number
        errorCode:
          $ref: './common.yml#/components/schemas/FaceRecognitionResultCode'
        errorMsg:
          type: string

    CompareImageDetection:
      type: object
      required:
        - imageIndex
        - status
      properties:
        faces:
          type: array
          items:
            $ref: "#/components/schemas/DetectionFace"
        imageIndex:
          $ref: "#/components/schemas/CompareImageIndex"
        status:
          $ref: './common.yml#/components/schemas/FaceRecognitionResultCode'

    DetectionFace:
      type: object
      properties:
        faceIndex:
          $ref: "#/components/schemas/CompareFaceIndex"
        landmarks:
          description: "Main coordinates of the detected face (eyes, nose, lips, ears and etc.)."
          type: array
          items:
            description: "Cartesian points. First element - X-axis coordinate. Second element - Y-axis coordinate."
            type: array
            items:
              type: number
              example: [ x, y ]
          example: [ [ x, y ] ]
        roi:
          $ref: "./common.yml#/components/schemas/FaceRectangular"
        thumbnail:
          $ref: "./common.yml#/components/schemas/Thumbnail"

    ImageSource:
      description: "Face photo image source"
      type: integer
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
      x-enum-varnames:
        - DOCUMENT_PRINTED
        - DOCUMENT_RFID
        - LIVE
        - DOCUMENT_WITH_LIVE
        - EXTERNAL
