openapi: 3.0.3
paths:

  /compare:
    post:
      tags:
        - matching
      summary: "Compare provided face images in all combinations and return similarity score for each pair."
      operationId: compare
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompareRequest"
      responses:
        200:
          description: "Successful operation; return compare results with their score and similarity."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompareResponse"
        400:
          $ref: "./common.yml#/components/responses/BadRequest"
        403:
          $ref: "./common.yml#/components/responses/BadLicense"

components:
  schemas:

    CompareRequest:
      type: object
      required:
        - images
      properties:
        images:
          type: array
          items:
            $ref: "#/components/schemas/CompareImage"

    CompareImage:
      type: object
      required:
        - data
      properties:
        index:
          type: number
        type:
          $ref: "#/components/schemas/ImageSource"
        data:
          $ref: "./common.yml#/components/schemas/ImageData"

    CompareResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/CompareImageResult"

    CompareImageResult:
      type: object
      properties:
        firstIndex:
          type: number
        secondIndex:
          type: number
        score:
          type: number
        similarity:
          type: number
        errorCode:
          type: string
        errorMsg:
          type: string

    ImageSource:
      description: "Face photo image source"
      type: number
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
      x-enum-varnames:
        - DOCUMENT_PRINTED
        - DOCUMENT_RFID
        - LIVE
        - DOCUMENT_WITH_LIVE
        - EXTERNAL
