openapi: 3.0.3
paths:

  /detect:
    post:
      tags:
        - matching
      summary: "Detect facial coordinates"
      operationId: detect
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DetectRequest"
      responses:
        200:
          description: "Successful operation; return detection faces with their coordinates."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetectResponse"
        400:
          $ref: "./common.yml#/components/responses/BadRequest"
        403:
          $ref: "./common.yml#/components/responses/BadLicense"

components:
  schemas:

    DetectRequest:
      type: object
      properties:
        image:
          $ref: "./common.yml#/components/schemas/ImageData"
        only_central_face:
          description: "True - main face; false - all faces."
          type: boolean
          default: false

    DetectResponse:
      type: object
      properties:
        detections:
          type: array
          items:
            $ref: "#/components/schemas/Detection"
        detectorType:
          description: "The internal type of detector. Used to calculate the rectangular area of the detected face (roi)."
          type: integer
        landmarksType:
          description: "The internal type of detector. Used to calculate the main coordinate of the detected face (landmarks)."
          type: integer

    Detection:
      type: object
      properties:
        landmarks:
          description: "Main coordinates of the detected face."
          type: array
          items:
            type: array
            items:
              type: number
          example: [[x, y]]
        roi:
          description: "Rectangular area of the detected face."
          type: array
          items:
            type: number
          example: [x, y, weight, height]
