openapi: 3.0.3
paths:

  /detect:
    post:
      tags:
        - matching
      summary: "Detect facial coordinates"
      operationId: detect
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DetectRequest"
      responses:
        200:
          description: "Successful operation; return detection faces with their coordinates."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetectResponse"
        400:
          $ref: "./common.yml#/components/responses/BadRequest"
        403:
          $ref: "./common.yml#/components/responses/BadLicense"

components:
  schemas:

    DetectRequest:
      type: object
      properties:
        image:
          $ref: "./common.yml#/components/schemas/ImageData"
        only_central_face:
          description: "True - main face; false - all faces."
          type: boolean
          default: false

    DetectResponse:
      type: object
      required:
        - detections
      properties:
        detections:
          type: array
          items:
            $ref: "#/components/schemas/Detection"
        detectorType:
          description: "Internal."
          type: integer
        landmarksType:
          description: "Internal."
          type: integer

    Detection:
      type: object
      required:
        - landmarks
        - roi
      properties:
        landmarks:
          description: "Main coordinates of the detected face (eyes, nose, lips, ears and etc.)."
          type: array
          items:
            description: "Cartesian points. First element - X-axis coordinate. Second element - Y-axis coordinate."
            type: array
            items:
              type: number
              example: [x, y]
          example: [[x, y]]
        roi:
          $ref: "#/components/schemas/FaceRectangular"

    FaceRectangular:
      description: "Rectangular area of the detected face. First element - X-axis coordinate. Second element - Y-axis coordinate. (X, Y) - left top point. Third element - rectangular width. Fourth element - rectangular height."
      type: array
      items:
        type: number
      example: [x, y, width, height]
