openapi: 3.0.3
info:
  title: Regula Face Recognition Web API
  description: Regula Face Recognition Web API
  version: 0.1.0

servers:
  - url: http://localhost:41101/
    description: Local on-premise installation
  
paths:
  /compare:
    $ref: './comparison.yml#/paths/~1compare'
  /detect:
    $ref: './detect.yml#/paths/~1detect'
